groups:
- name: backtest
  rules:
  # Recording rules for backtest metrics
  - record: bt_runtime_ms_p95_5m
    expr: histogram_quantile(0.95, sum by (le) (rate(bt_runtime_ms_bucket[5m])))
    labels:
      component: "backtest"
      
  - record: bt_trades_total_5m
    expr: sum(rate(bt_trades_total[5m]))
    labels:
      component: "backtest"
      
  - record: bt_max_dd_5m
    expr: max_over_time(bt_max_dd[5m])
    labels:
      component: "backtest"
      
  - record: bt_sharpe_5m
    expr: avg_over_time(bt_sharpe[5m])
    labels:
      component: "backtest"

  # Alert rules for backtest monitoring
  - alert: BacktestSlowRunner
    expr: bt_runtime_ms_p95_5m > 30000
    for: 10m
    labels:
      severity: "warning"
      component: "backtest"
      team: "platform"
    annotations:
      summary: "Backtest P95 runtime > 30s"
      description: "Backtest engine is running slowly. P95 runtime: {{ $value }}ms"
      
  - alert: BacktestErrorSpike
    expr: increase(bt_errors_total[10m]) > 5
    for: 5m
    labels:
      severity: "warning"
      component: "backtest"
      team: "platform"
    annotations:
      summary: "Backtest error spike detected"
      description: "{{ $value }} backtest errors in the last 10 minutes"
      
  - alert: BacktestHighDrawdown
    expr: bt_max_dd_5m > 0.2
    for: 5m
    labels:
      severity: "warning"
      component: "backtest"
      team: "platform"
    annotations:
      summary: "Backtest high drawdown detected"
      description: "Max drawdown: {{ $value | humanizePercentage }}"
      
  - alert: BacktestNegativeSharpe
    expr: bt_sharpe_5m < 0
    for: 10m
    labels:
      severity: "info"
      component: "backtest"
      team: "platform"
    annotations:
      summary: "Backtest negative Sharpe ratio"
      description: "Average Sharpe ratio: {{ $value }}"