route:
  receiver: 'slack-sre'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 2h
  routes:
    - match_re:
        alertname: 'SLOBurn.*'
      receiver: 'slack-sre'

receivers:
  - name: 'slack-sre'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#war-room-spark'
        send_resolved: true
        title: '[{{ .CommonLabels.env | default "dev" }}] {{ .CommonAnnotations.summary }}'
        text: >-
          *Service:* spark-web

          *Severity:* {{ .CommonLabels.severity }}

          *Description:* {{ .CommonAnnotations.description }}

          *Runbook:* {{ .CommonAnnotations.runbook | default "n/a" }}

          *Dashboard:* {{ .CommonAnnotations.dashboard | default "n/a" }}

# KULLANIM:
# 1. SLACK_WEBHOOK_URL environment variable set et:
#    export SLACK_WEBHOOK_URL=https://hooks.slack.com/services/YOUR/WEBHOOK/URL
#
# 2. Alertmanager başlat:
#    docker run -d -p 9093:9093 \
#      -v $(pwd)/monitoring/alertmanager:/etc/alertmanager \
#      -e SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL \
#      prom/alertmanager
#
# 3. Test notification:
#    curl -X POST http://localhost:9093/api/v1/alerts -d '[{"labels":{"alertname":"test"}}]'

