version: "3.9"
services:
  executor:
    build:
      context: .
      dockerfile: packages/executor/Dockerfile
    environment:
      - PORT=4001
      - NODE_ENV=production
    ports:
      - "4001:4001"
    networks: [ sparknet ]

  web:
    build:
      context: .
      dockerfile: apps/web-next/Dockerfile
    environment:
      - PORT=3003
      - HOST=0.0.0.0
      - NEXT_PUBLIC_EXECUTOR_ORIGIN=http://executor:4001
    depends_on:
      - executor
    ports:
      - "3003:3003"
    networks: [ sparknet ]

networks:
  sparknet: {} 