name: metrics-guard
on: [push, workflow_dispatch]

jobs:
  metric_guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 10.14.0 }
      - run: pnpm -w install
      
      - name: Build streams + executor
        run: |
          pnpm -F @spark/streams build
          pnpm -F @spark/executor build
          
      - name: Start executor
        run: |
          pnpm -F @spark/executor start &
          sleep 10
          
      - name: Check streams metrics
        run: |
          curl -s http://localhost:4001/metrics | grep -E "(ws_msgs_total|ingest_latency_ms_bucket|ws_gap_ms_bucket)" || exit 1
          
      - name: Check metrics rate
        run: |
          # Check if metrics are being generated
          curl -s http://localhost:4001/metrics | grep "ws_msgs_total" | head -1
          
      - name: Check latency threshold
        run: |
          # This would check P95 latency < 300ms in a real scenario
          echo "Latency check would be implemented here"
          
      - name: Cleanup
        run: |
          pkill -f "executor" || true
