global:
  scrape_interval: 5s
scrape_configs:
  - job_name: executor
    static_configs: [{ targets: ["host.docker.internal:4001"] }]
  - job_name: web
    static_configs: [{ targets: ["host.docker.internal:3003"] }]