CREATE TABLE IF NOT EXISTS ohlcv(
  ts BIGINT NOT NULL,
  exchange TEXT NOT NULL,
  symbol TEXT NOT NULL,
  tf TEXT NOT NULL,
  o NUMERIC NOT NULL, h NUMERIC NOT NULL, l NUMERIC NOT NULL, c NUMERIC NOT NULL,
  v DOUBLE PRECISION NOT NULL, qv DOUBLE PRECISION, n INT, vwap DOUBLE PRECISION,
  PRIMARY KEY (exchange, symbol, tf, ts)
);
CREATE INDEX IF NOT EXISTS ohlcv_brin_ts ON ohlcv USING BRIN(ts);
CREATE INDEX IF NOT EXISTS ohlcv_symbol_tf ON ohlcv(symbol, tf);
