groups:
- name: private_api
  rules:
  - alert: PrivateAPIErrorRateHigh
    expr: (rate(spark_private_errors_total[5m]) / clamp_min(rate(spark_private_calls_total[5m]), 1e-9)) > 0.05
    for: 10m
    labels: { severity: warning }
    annotations:
      summary: "Private API error rate > 5% for 10m"
  - alert: PrivateAPINoCalls
    expr: rate(spark_private_calls_total[10m]) == 0
    for: 15m
    labels: { severity: info }
    annotations:
      summary: "No private calls in last 10m" 