apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: '15s'
      httpMethod: 'POST'

# KULLANIM:
# Bu dosya Grafana'ya Prometheus datasource'u otomatik ekler.
# Docker Compose ile kullanırken prometheus:9090 hostname çözülür.
# Standalone kullanımda url'i http://localhost:9090 yapın.

