# Grafana Datasource Provisioning
# Prometheus datasource for Spark Platform

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations: []
      timeInterval: "10s"
    version: 1

