name: GUARD DEMO — should FAIL

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

concurrency:
  group: guard-demo-${{ github.ref }}
  cancel-in-progress: true

jobs:
  demo-fail:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Demo step with secret (NO FORK GUARD - intentionally broken)
        shell: pwsh
        env:
          DEMO_SECRET: ${{ secrets.DEMO_SECRET || 'fallback' }}
        run: |
          Write-Host "This step uses a secret without fork guard"
          Write-Host "Guard validator should FAIL this workflow"
          Write-Host "Demo secret: $env:DEMO_SECRET"

