name: Block node_modules in PRs
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fail if node_modules is added
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          if git diff --name-only origin/${{ github.base_ref }}... | grep -E '^node_modules/|/node_modules/'; then
            echo "❌ node_modules detected in PR - please remove it"
            exit 1
          else
            echo "✅ No node_modules in PR"
          fi

