name: Database Drift Check

on:
  pull_request:
    paths:
      - 'prisma/**'
      - '**/prisma/**'
      - 'services/**/schema.prisma'

jobs:
  drift-check:
    name: Prisma Schema Drift Detection
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: spark_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      
      - name: Verify pnpm version
        run: |
          EXPECTED=$(node -p "require('./package.json').packageManager.split('@')[1]")
          ACTUAL=$(pnpm -v)
          test "$ACTUAL" = "$EXPECTED" || { echo "::error::pnpm mismatch"; exit 1; }
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies
      
      - name: Generate Prisma Client
        run: pnpm exec prisma generate
      
      - name: Apply migrations to test database
        run: pnpm exec prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:test_password@localhost:5432/spark_test
      
      - name: Check for schema drift
        run: |
          pnpm exec prisma migrate diff \
            --from-schema-datamodel prisma/schema.prisma \
            --to-url "$DATABASE_URL" \
            --exit-code
        env:
          DATABASE_URL: postgresql://postgres:test_password@localhost:5432/spark_test
      
      - name: Upload migration evidence
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: drift-diff
          path: |
            prisma/migrations/**/*.sql
            evidence/drift_*.txt

