name: desktop-release

on:
  push:
    tags: ["v*"]
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: windows-latest
    env:
      SPARK_UPDATE_CHANNEL: ${{ contains(github.ref_name, '-beta') && 'beta' || 'stable' }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - run: pnpm -w install

      - name: Export deploy secrets to env
        shell: pwsh
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
        run: |
          $port = if ($env:DEPLOY_PORT) { $env:DEPLOY_PORT } else { '22' }
          echo "DEPLOY_HOST=$env:DEPLOY_HOST" >> $env:GITHUB_ENV
          echo "DEPLOY_USER=$env:DEPLOY_USER" >> $env:GITHUB_ENV
          echo "DEPLOY_PATH=$env:DEPLOY_PATH" >> $env:GITHUB_ENV
          echo "DEPLOY_PORT=$port" >> $env:GITHUB_ENV

      - name: Export code-signing secrets to env
        shell: pwsh
        env:
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
        run: |
          echo "CSC_LINK=$env:WIN_CSC_LINK" >> $env:GITHUB_ENV
          echo "CSC_KEY_PASSWORD=$env:WIN_CSC_KEY_PASSWORD" >> $env:GITHUB_ENV

      - name: Add SSH key to agent (webfactory)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Known hosts
        shell: bash
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${DEPLOY_PORT}" "${DEPLOY_HOST}" >> ~/.ssh/known_hosts

      - name: Build desktop (dist:win)
        run: pnpm -w --filter desktop-electron dist:win

      - name: Publish artifacts via scp
        shell: bash
        run: |
          SRC="apps/desktop-electron/dist"
          DST="${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/${SPARK_UPDATE_CHANNEL}/"
          scp -P "${DEPLOY_PORT}" "${SRC}/latest.yml" "${DST}"
          EXE="$(ls "${SRC}"/Spark\ Trading\ Setup\ *.exe | head -n1)"
          scp -P "${DEPLOY_PORT}" "${EXE}" "${DST}"
