name: Docs Link Check
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docs-linkcheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Link Check (lychee)
        uses: lycheeverse/lychee-action@v1
        with:
          args: --exclude-mail -v **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
