name: docs-lint
on:
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.*'
permissions:
  contents: read
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm -w install --frozen-lockfile
      - name: Run markdownlint-cli2 (config + ignores)
        run: |
          pnpm -w dlx markdownlint-cli2 --config .markdownlint.jsonc \
            "**/*.md" "!**/node_modules/**" "!evidence/**" "!.evidence/**" "!apps/**/.next/**" "!apps/**/dist/**"