name: Docs Lint

on:
  pull_request:
    paths:
      - "docs/**"
      - "README.md"
      - ".markdownlint*"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run markdownlint-cli2
        run: npx -y markdownlint-cli2 **/*.md "#node_modules" "#.next" "#evidence" "#GPT_Backups"
