name: Guard Audit (Weekly)

on:
  schedule:
    # Every Monday at 09:00 Istanbul time (06:00 UTC)
    - cron: '0 6 * * 1'
  workflow_dispatch:

concurrency:
  group: guard-audit
  cancel-in-progress: false

jobs:
  audit:
    name: Weekly Fork Guard Audit
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate all workflow fork guards
        shell: pwsh
        run: ./.github/scripts/validate-workflow-guards.ps1
      
      - name: Report results
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Weekly guard audit: ALL WORKFLOWS PROTECTED"
          else
            echo "❌ Weekly guard audit: SOME GUARDS MISSING"
            echo "::warning title=Guard Audit Failed::Some workflows lack fork guards. Run .github/scripts/validate-workflow-guards.ps1 locally for details."
            exit 1
          fi
      
      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔐 Weekly Guard Audit Failed',
              body: `Weekly fork guard audit detected missing guards.\n\n**Run:** ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}\n\n**Action Required:**\nRun \`.github/scripts/validate-workflow-guards.ps1\` locally to identify which workflows need guards.`,
              labels: ['security', 'ci', 'high-priority']
            });

