name: Lighthouse CI (Canary)

on:
  pull_request:
    branches: [main]
    paths:
      - "apps/web-next/**"
      - ".github/workflows/lighthouse.yml"
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: true # Canary mode

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.3

      - name: Install dependencies
        run: |
          set -euxo pipefail
          pnpm -w install --frozen-lockfile || pnpm -w install

      - name: Build web-next
        run: pnpm --filter web-next build
        env:
          NODE_ENV: production

      - name: Start web-next
        working-directory: apps/web-next
        env:
          NODE_ENV: production
          PORT: 3003
          HOSTNAME: 127.0.0.1
        run: |
          set -e
          if [ -f ".next/standalone/server.js" ]; then
            nohup node .next/standalone/server.js > ../../lh-server.log 2>&1 &
          else
            nohup npx next start -p 3003 -H 127.0.0.1 > ../../lh-server.log 2>&1 &
          fi

      - name: Wait for health
        run: |
          set -e
          for i in $(seq 1 60); do
            if curl -fsS http://127.0.0.1:3003/api/health >/dev/null 2>&1; then
              echo "✅ Server ready"
              exit 0
            fi
            sleep 2
          done
          echo "❌ Server timeout"
          exit 1

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x

      - name: Run Lighthouse
        run: |
          lhci autorun \
            --collect.url=http://127.0.0.1:3003 \
            --upload.target=temporary-public-storage || echo "⚠️ Lighthouse warnings (canary mode)"

      - name: Upload Lighthouse results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: |
            .lighthouseci/**/*
            lh-server.log
          retention-days: 7

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-debug
          path: |
            lh-server.log
            apps/web-next/.next/**
          retention-days: 1
