name: UI Smoke (web-next)

on:
  pull_request:
    paths:
      - 'apps/web-next/**'
      - '!apps/web-next/**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    name: Web-Next Health Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      
      - name: Verify pnpm version
        run: |
          EXPECTED=$(node -p "require('./package.json').packageManager.split('@')[1]")
          ACTUAL=$(pnpm -v)
          test "$ACTUAL" = "$EXPECTED" || { echo "::error::pnpm mismatch"; exit 1; }
      
      - name: Fetch dependencies
        run: pnpm fetch --prod=false
      
      - name: Install (offline)
        run: pnpm install --offline --frozen-lockfile --strict-peer-dependencies
      
      - name: Build web-next
        run: pnpm -F web-next build
      
      - name: Start web-next (background)
        run: |
          pnpm -F web-next start -p 3100 &
          echo $! > webnext.pid
          sleep 10
      
      - name: Probe mock endpoints
        run: |
          echo "Testing error budget endpoint..."
          curl -fsS http://127.0.0.1:3100/api/public/error-budget | jq .status
          
          echo "Testing engine health endpoint..."
          curl -fsS http://127.0.0.1:3100/api/public/engine-health | jq .status
          
          echo "✅ All health endpoints responding"
      
      - name: Stop server
        if: always()
        run: |
          if [ -f webnext.pid ]; then
            kill $(cat webnext.pid) || true
          fi

