name: ui-smoke

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: corepack enable && corepack prepare pnpm@10.0.0 --activate
      - run: pnpm -w i --frozen-lockfile=false
      - run: pnpm -w --filter web-next build
      - run: pnpm -w --filter web-next start:prod &
      - run: npx wait-on http://127.0.0.1:3003
      - name: Smoke endpoints (6x 200)
        run: |
          set -e
          for p in "/" "/portfolio" "/strategies" "/running" "/settings" "/api/health"; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:3003${p})
            [ "$code" = "200" ] || (echo "FAIL $p => $code" && exit 1)
          done
          echo "SMOKE PASS"
