name: UX-ACK Gate

on:
  pull_request:
    branches: [ main ]

jobs:
  ux-ack:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body contains "UX-ACK: approved"
        shell: bash
        run: |
          BODY="${{ github.event.pull_request.body }}"
          echo "PR body (first 200 chars):"
          echo "$BODY" | cut -c1-200
          echo
          echo "Checking for 'UX-ACK: approved'..."
          echo "$BODY" | grep -qiE '^UX-ACK:\s*approved' && {
            echo "UX-ACK present ✅"
          } || {
            echo "UX-ACK missing ❌"
            exit 1
          }
