name: UX-ACK Gate

on:
  pull_request:
    types: [opened, edited, synchronize, labeled]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ux_ack:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr_labels
        run: |
          $labels = ${{ toJson(github.event.pull_request.labels.*.name) }}
          Write-Host "PR Labels: $labels"
          echo "labels=$labels" >> $GITHUB_OUTPUT

      - name: Check for UX-ACK label
        shell: pwsh
        run: |
          $labels = '${{ steps.pr_labels.outputs.labels }}'
          Write-Host "Checking for UX-ACK label or marker..."
          
          if ($labels -match 'UX-ACK') {
            Write-Host "[PASS] UX-ACK label found"
            exit 0
          }
          
          # Fallback: Check PR body
          $body = @'
          ${{ github.event.pull_request.body }}
          '@
          
          if ($body -match 'UX-ACK:') {
            Write-Host "[PASS] UX-ACK marker found in PR description"
            exit 0
          } else {
            Write-Host "[FAIL] UX-ACK not found in labels or PR description"
            Write-Host ""
            Write-Host "Please either:"
            Write-Host "1. Add 'UX-ACK' label to the PR, or"
            Write-Host "2. Add to PR description: UX-ACK: [your acknowledgment message]"
            exit 1
          }
