name: ux-ack
on:
  pull_request:
    types: [opened, edited, synchronize, labeled, unlabeled, ready_for_review]
permissions:
  pull-requests: read
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect docs-only changes
        id: docs
        run: |
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          echo "$CHANGED" | awk '!/^(docs\/|README.md$|\.github\/)/{exit 1}'; RC=$?
          if [ $RC -eq 0 ]; then echo "docs_only=true" >> $GITHUB_OUTPUT; else echo "docs_only=false" >> $GITHUB_OUTPUT; fi
      - name: Bypass for docs-only
        if: steps.docs.outputs.docs_only == 'true'
        run: echo "Docs-only change → UX-ACK bypass PASS"
      - name: Require UX-ACK label
        if: steps.docs.outputs.docs_only != 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          NUM=${{ github.event.pull_request.number }}
          echo "Checking UX-ACK label on PR #$NUM"
          LABELS=$(gh pr view $NUM --json labels --jq '.labels[].name')
          echo "$LABELS" | grep -q '^UX-ACK$' && echo "Found UX-ACK label ✅" || (echo "Missing UX-ACK label ❌" && exit 1)