name: UX-ACK Gate

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ux_ack:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body for UX-ACK
        shell: pwsh
        run: |
          $body = @'
          ${{ github.event.pull_request.body }}
          '@

          Write-Host "Checking PR body for UX-ACK marker..."

          if ($body -match 'UX-ACK:') {
            Write-Host "[PASS] UX-ACK marker found in PR description"
            exit 0
          } else {
            Write-Host "[FAIL] UX-ACK marker not found in PR description"
            Write-Host ""
            Write-Host "Please add the following to your PR description:"
            Write-Host "UX-ACK: [your acknowledgment message]"
            exit 1
          }
